server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT}

spring:
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs/raw
  swagger-ui:
    path: /swagger/index.html
    persist-authorization: true
  show-login-endpoint: true







